### ISSUE TITLE
torch._cudnn_rnn_flatten_weight - cuDNN error: CUDNN_STATUS_NOT_INITIALIZED ?

### ISSUE THREAD

**Issue by docelic** [clarinsi/classla-stanfordnlp#12]
When running the basic example, we get:

```
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 172, in flatten_parameters
    torch._cudnn_rnn_flatten_weight(
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

Any obvious hints/pointers? Thanks!

**Comment by nljubesi** [comment]
Hi, could you give us more details, at least 1. how you installed the tool (what version, if you used pip) and 2. what is the exact example / command you are running? Thanks!

**Comment by lkrsnik** [comment]
This looks like an issue on torch - GPU relation. As a quick solution you might try running classla on CPU:

`classla.Pipeline(..., use_gpu=False)`

**Comment by docelic** [comment]
Heya, sure:

Pip/python:
```pip3 --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

python3 --version
Python 3.8.5
```

classla installed just with `pip3 install classla`:
```
pip3 list |grep classla
classla                 1.0.0
```

nvcc (if relevant):
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

Example program (copied as is from the website):

```
import classla
classla.download('sl')
nlp = classla.Pipeline('sl')
doc = nlp("France Prešeren je rojen v Vrbi.")
print(doc.to_conll())
```

Running it:
```
python3 test.py
Downloading https://raw.githubusercontent.com/clarinsi/classla-resources/main/resources_1.0.0.json: 10.3kB [00:00, 4.23MB/s]                                                
2021-03-12 15:16:21 INFO: Downloading these customized packages for language: sl (Slovenian)...
========================
| Processor | Package  |
------------------------
| tokenize  | standard |
| pos       | standard |
| lemma     | standard |
| depparse  | standard |
| ner       | standard |
| pretrain  | standard |
========================

2021-03-12 15:16:22 INFO: File exists: /home/user/classla_resources/sl/pos/standard.pt.
2021-03-12 15:16:22 INFO: File exists: /home/user/classla_resources/sl/lemma/standard.pt.
2021-03-12 15:16:22 INFO: File exists: /home/user/classla_resources/sl/depparse/standard.pt.
2021-03-12 15:16:22 INFO: File exists: /home/user/classla_resources/sl/ner/standard.pt.
2021-03-12 15:16:23 INFO: File exists: /home/user/classla_resources/sl/pretrain/standard.pt.
2021-03-12 15:16:23 INFO: Finished downloading models and saved to /home/user/classla_resources.
2021-03-12 15:16:23 INFO: Loading these models for language: sl (Slovenian):
========================
| Processor | Package  |
------------------------
| tokenize  | standard |
| pos       | standard |
| lemma     | standard |
| depparse  | standard |
| ner       | standard |
========================

2021-03-12 15:16:23 INFO: Use device: gpu
2021-03-12 15:16:23 INFO: Loading: tokenize
2021-03-12 15:16:23 INFO: Loading: pos
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    nlp = classla.Pipeline('sl')
  File "/home/user/.local/lib/python3.8/site-packages/classla/pipeline/core.py", line 112, in __init__
    self.processors[processor_name] = NAME_TO_PROCESSOR_CLASS[processor_name](config=curr_processor_config,
  File "/home/user/.local/lib/python3.8/site-packages/classla/pipeline/processor.py", line 146, in __init__
    self._set_up_model(config, use_gpu)
  File "/home/user/.local/lib/python3.8/site-packages/classla/pipeline/pos_processor.py", line 33, in _set_up_model
    self._trainer = Trainer(args=arg, pretrain=self.pretrain, model_file=config['model_path'], use_cuda=use_gpu)
  File "/home/user/.local/lib/python3.8/site-packages/classla/models/pos/trainer.py", line 53, in __init__
    self.model.cuda()
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 491, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 186, in _apply
    self.flatten_parameters()
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 172, in flatten_parameters
    torch._cudnn_rnn_flatten_weight(
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

Thanks!

**Comment by docelic** [comment]
@lkrsnik indeed, with `use_gpu=False` it works. Any ideas what the issue could be when cuda is used?

**Comment by docelic** [comment]
The error happens even though torch thinks the cuDNN backend exists and is enabled:

```
print(torch.backends.cudnn.is_available())
print(torch.backends.cudnn.version())
print(torch.backends.cudnn.enabled)

True
7605
True
```

**Comment by docelic** [comment]
Hello,

We solved the issue - this is a bug in Torch 1.8.0. The solution is to revert to 1.7.1:

```
pip uninstall torch
pip install torch==1.7.1
```

And to update to Torch 1.8.1 when it gets released - it will supposedly have this fixed.

Thanks for your help.

**Comment by sjkoelle** [comment]
I'm currently seeing `CUDA error: no kernel image is available for execution on the device` on ` torch._cudnn_rnn_flatten_weight` when calling `model.cuda()` with

```
print(torch.backends.cudnn.is_available())
print(torch.backends.cudnn.version())
print(torch.backends.cudnn.enabled)

True
7605
True

print(torch.cuda.get_arch_list())
[‘sm_37’, ‘sm_50’, ‘sm_60’, ‘sm_70’]

!nvcc --version
Build cuda_11.2.r11.2/compiler.29558016_0
```

and torch `1.9.0+cu102`, but only on a machine with an A6000 gpu.  Our T4 machine seems to be fine (although all the outputted versions are the same).
